l5/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    //
});


Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/home', 'HomeController@index');
});

Route::get('Contact' , [
    'as' => 'Eshopper.contact',
    'uses'=>'StaticController@contact'
]) ;

Route::get('/index', [
        'as' => 'eshopper.index',
        'uses' => 'IndexController@index'
    ]
);
// product routes
Route::resource('products',  'ProductController') ;

// products of  categories routes

Route::get('category/{catId}/products', [
    'as' => 'eshopper.category.products' ,
    'uses'=> 'CategoryController@productsOfCategoryAndSub'
]);

// blog rotues

Route::resource('posts' , 'PostController') ;

// Cart routes

Route::get('cart', [
    'as' => 'Eshopper.cart' ,
    'uses' =>'CartController@show'
]) ;

l5/resources/views/blog/post-single.blade.php
@extends('layouts.app')

@section('content')
    <section>
        <div class="container">
            <div class="row">
                @include('partials.sidebar')
                <div class="col-sm-9">

                    <div class="blog-post-area">
                        <h2 class="title text-center">Latest From our Blog</h2>
                            <div class="single-blog-post">
                                <h3>{{$post->title}}</h3>
                                <div class="post-meta">
                                    <ul>
                                        <li><i class="fa fa-user"></i> {{$post->user->name}}</li>
                                        <li><i class="fa fa-clock-o"></i> {{date_format($post->created_at,"H:i")}}</li>
                                        <li><i class="fa fa-calendar"></i> {{date_format($post->created_at,"d/m , y")}}</li>
                                    </ul>
								<span>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
								</span>
                                </div>
                                <a href="">
                                    <img src="{{$post->image_path}}" alt="">
                                </a>
                                <p> {{$post->body}}</p>
                                <div class="pager-area">
                                    <ul class="pager pull-right">
                                        @if($previousPost)
                                            <li><a href="{{url('posts/'.$previousPost)}}">Pre</a></li>
                                        @endif
                                        @if($nextPost)
                                            <li><a href="{{url('posts/'.$nextPost)}}">Next</a></li>
                                        @endif

                                    </ul>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop

l5/resources/views/blog/posts.blade.php
@extends('layouts.app')

@section('content')
    <section>
        <div class="container">
            <div class="row">
                @include('partials.sidebar')
                <div class="col-sm-9">

                    <div class="blog-post-area">
                        <h2 class="title text-center">Latest From our Blog</h2>
                        @foreach($posts as $post )
                            <div class="single-blog-post">
                                <h3>{{$post->title}}</h3>
                                <div class="post-meta">
                                    <ul>
                                        <li><i class="fa fa-user"></i> {{$post->user->name}}</li>
                                        <li><i class="fa fa-clock-o"></i> {{date_format($post->created_at,"H:i")}}</li>
                                        <li><i class="fa fa-calendar"></i> {{date_format($post->created_at,"d/m , y")}}</li>
                                    </ul>
								<span>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
								</span>
                                </div>
                                <a href="">
                                    <img src="{{$post->image_path}}" alt="">
                                </a>
                                <p> {{str_limit($post->body, 100)}}</p>
                                <a class="btn btn-primary" href="{{route('posts.show',$post->id)}}">Read More</a>
                            </div>
                        @endforeach
                        <div class="pagination-area">
                            {{with(new Eshopper\Repositories\EshopperPresenter($posts))->render()}}
                        </div>
{{--                        {{ $posts->links('partials.pagination.default') }}--}}
{{--                        @include('partials.pagination.default', ['paginator', $posts])--}}

                    </div>
                </div>
            </div>
        </div>
    </section>
@stop