l5/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    //
});


Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/home', 'HomeController@index');
});

Route::get('Contact' , [
    'as' => 'Eshopper.contact',
    'uses'=>'StaticController@contact'
]) ;

Route::get('/index', [
        'as' => 'eshopper.index',
        'uses' => 'IndexController@index'
    ]
);
// product routes
Route::resource('products',  'ProductController') ;

// products of  categories routes

Route::get('category/{catId}/products', [
    'as' => 'eshopper.category.products' ,
    'uses'=> 'CategoryController@productsOfCategoryAndSub'
]);

// blog rotues

Route::resource('posts' , 'PostController') ;

// Cart routes

Route::get('cart', [
    'as' => 'Eshopper.cart' ,
    'uses' =>'CartController@show'
]) ;

l5/app/Product.php
<?php

namespace Eshopper;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
            'name' ,
            'description' ,
            'reference' ,
            'rating' ,
            'details',
    ] ;


    public function  prices () {
        return $this->hasMany('Eshopper\Price') ;
    }

    public function  stock () {
        return $this->belongsTo('Eshopper\Stock') ;
    }

    public function  availability() {
        return $this->belongsTo('Eshopper\Availability') ;
    }

    public function  condition() {
        return $this->belongsTo('Eshopper\Condition') ;
    }
    public function  state() {
        return $this->belongsTo('Eshopper\State') ;
    }

    public function  images () {
        return  $this->hasMany('Eshopper\Image') ;
    }

    public function  brand() {
        return $this->belongsTo('Eshopper\Brand') ;
    }

    public function category() {
        return $this->belongsTo('Eshopper\Category') ;
    }
}

l5/app/Http/Controllers/ProductController.php
<?php

namespace Eshopper\Http\Controllers;

use Eshopper\Repositories\BrandRepository;
use Eshopper\Repositories\CategoryRepository;
use Eshopper\Repositories\ProductRepository;
use Illuminate\Http\Request;

use Eshopper\Http\Requests;
use Eshopper\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class ProductController extends Controller
{
    protected  $productRepository   ;
    protected  $brandRepository ;
    protected  $categoryRepository;

    public function  __construct( ProductRepository $productRepository, BrandRepository $brandRepository,  CategoryRepository $categoryRepository){

        $this->productRepository = $productRepository ;
        $this->brandRepository = $brandRepository ;
        $this->categoryRepository = $categoryRepository ;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = $this->productRepository->getPaginatedProducts(10) ;

        return  view('products.products')->with('products' , $products) ;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = $this->productRepository->getAllProductInfo($id) ;

        return view('products.product-details')->with('product', $product) ;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


}

l5/resources/views/products/product-details.blade.php
@extends('layouts.app')


@section('content')
    <section>
        <div class="container">
            <div class="row">
                @include('partials.sidebar')
                <div class="product-details"><!--product-details-->
                    <div class="col-sm-5">
                        <div class="view-product">
                            <img src="{{$product->images[0]->image_path}}" alt=""/>
                            <h3>ZOOM</h3>
                        </div>
                        <div id="similar-product" class="carousel slide" data-ride="carousel">
                            <!-- Wrapper for slides -->
                            <div class="carousel-inner">
                                <?php $i = 0 ;  $temp= 0 ?>

                                @for($i= 0 ;  $i < count($product->images); $i++)
                                    @if($i % 3== 0)
                                            <div class="item {{ ($i==0) ? 'active' :''}}">
                                    @endif
                                    <?php $j= $i ;?>

                                    @for($j= $i ;  $j < $i+3;$j++)
                                                @if($j < count($product->images))
                                                 <a href=""><img src="{{$product->images[$j]->image_path}}" alt="" width="90px" ></a>
                                                        <?php $temp=  $j; ?>
                                                @endif
                                    @endfor

                                    @if($i % 3 == 0)
                                        </div>
                                    @endif
                                    <?php $i=  $temp ; ?>
                                    @endfor

                            </div>

                            <!-- Controls -->
                            <a class="left item-control" href="#similar-product" data-slide="prev">
                                <i class="fa fa-angle-left"></i>
                            </a>
                            <a class="right item-control" href="#similar-product" data-slide="next">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>
                    </div>
                    <div class="col-sm-7">
                        <div class="product-information"><!--/product-information-->
                            <img src="/images/product-details/new.jpg" class="newarrival" alt=""/>
                            <h2>{{$product->name}}</h2>
                            <p>Web ID: {{$product->reference}}</p>
                            <img src="/images/product-details/rating.png" alt=""/>
								<span>
									<span>US ${{$product->prices()->first()->value}}</span>
									<label>Quantity:</label>
                                     <input value="{{$product->stock->quantity}}" readonly>
									<button type="button" class="btn btn-fefault cart">
                                        <i class="fa fa-shopping-cart"></i>
                                        Add to cart
                                    </button>
								</span>
                            <p><b>Availability: {{$product->availability->type}}</b></p>
                            <p><b>Condition:</b> {{$product->condition->value}}</p>
                            <p><b>Brand:</b> E-SHOPPER</p>
                            <a href=""><img src="/images/product-details/share.png" class="share img-responsive"
                                            alt=""/></a>
                        </div><!--/product-information-->
                    </div>
                </div><!--/product-details-->

            </div>
        </div>
    </section>
@stop

l5/resources/views/products/product-not-found.blade.php
@extends('layouts.app')

@section('content')

    <div class="container text-center">
        <div class="logo-404">
            <a href="index.html"><img src="/images/home/logo.png" alt=""/></a>
        </div>
        <div class="content-404">
            <img src="/images/404/404.png" class="img-responsive" alt=""/>
            <h1>{{$message}} {{$product_name}}</h1>
            <p>{{$detailed_message}}</p>
            <h2><a href="{{route('eshopper.index')}}">Bring me back Home</a></h2>
        </div>
    </div>
@stop

l5/resources/views/products/products-by-category.blade.php
@extends('layouts.app')
@section('content')
    <section>
        <div class="container">
            <div class="row">
                @include('partials.sidebar')
                <div class="col-sm-9">
                    <div class="row">

                        @foreach($products  as $product)
                            <div class="col-sm-3" >
                                <div class="product-image-wrapper">
                                    <div class="single-products">
                                        <div class="productinfo text-center">
                                            @if($product->images()->first())
                                                <img src="{{$product->images()->first()['image_path']}}" alt=""/>
                                            @endif
                                            <h2>${{$product->prices()->first()['value']}}</h2>
                                            <p>{{$product->name}}</p>
                                            <a href="#" class="btn btn-default add-to-cart"><i
                                                        class="fa fa-shopping-cart"></i>Add
                                                to cart</a>
                                        </div>
                                        <div class="product-overlay">
                                            <div class="overlay-content">
                                                <span> <a href="{{route('products.show',$product->id )}}"> Product
                                                        Details</a></span>
                                                <h2>${{$product->prices()->first()['value']}}</h2>
                                                <p>{{$product->name}}</p>
                                                <a href="#" class="btn btn-default add-to-cart"><i
                                                            class="fa fa-shopping-cart"></i>Add
                                                    to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="choose">
                                        <ul class="nav nav-pills nav-justified">
                                            <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                                            <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>

    </section>
@stop

l5/resources/views/products/products.blade.php
@extends('layouts.app')

@section('content')
    <section>
        <div class="container">
            <div class="row">
                @include('partials.sidebar')
                <div class="col-sm-9">
                    <div class="row">
                        @foreach($products  as $product)
                            <div class="col-sm-3" >
                                <div class="product-image-wrapper">
                                    <div class="single-products">
                                        <div class="productinfo text-center">
                                            @if($product->images()->first())
                                                <img src="{{$product->images()->first()['image_path']}}" alt=""/>
                                            @endif
                                            <h2>${{$product->prices()->first()['value']}}</h2>
                                            <p>{{$product->name}}</p>
                                            <a href="#" class="btn btn-default add-to-cart"><i
                                                        class="fa fa-shopping-cart"></i>Add
                                                to cart</a>
                                        </div>
                                        <div class="product-overlay">
                                            <div class="overlay-content">
                                                <span> <a href="{{route('products.show',$product->id )}}"> Product
                                                        Details</a></span>
                                                <h2>${{$product->prices()->first()['value']}}</h2>
                                                <p>{{$product->name}}</p>
                                                <a href="#" class="btn btn-default add-to-cart"><i
                                                            class="fa fa-shopping-cart" ></i>
                                                    Add to cart
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="choose">
                                        <ul class="nav nav-pills nav-justified">
                                            <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                                            <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop